services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      -  "/c/Users/swong/data-engineering-zoomcamp/01-docker-terraform/2_docker_sql/ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
      #- "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - "pgadmin_conn_data:/var/lib/pgadmin:rw"
    ports:
      - "8080:80"
  ingest_taxi_trips_data:
    build:
      dockerfile: Dockerfile
    command:
        - --user=root
        - --password=root
        - --host=pgdatabase
        - --port=5432
        - --db=ny_taxi
        - --table_name=green_taxi_trips
        - --url=https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-09.csv.gz
        #- --url=https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-01.csv.gz
    depends_on:
      - pgdatabase
      - pgadmin
  ingest_taxi_zone_data:
    build:
      dockerfile: Dockerfile
    command:
        - --user=root
        - --password=root
        - --host=pgdatabase
        - --port=5432
        - --db=ny_taxi
        - --table_name=taxi_zone
        - --url=https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv
    depends_on:
      - pgdatabase
      - pgadmin
      - ingest_taxi_trips_data

volumes:
  pgadmin_conn_data:

